jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        # Symfony Standard
        #Symfony\Component\Security\Core\User\User: plaintext
        # FOS
        FOS\UserBundle\Model\UserInterface: md5

    role_hierarchy:
        #Symfony Standard
        #ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        #FOS
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        # Symfony Standard
  #      in_memory:
  #          memory:
  #              users:
  #                  user:  { password: userpass, roles: [ 'ROLE_USER' ] }
 #                   admin2: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        # FOS
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # FOS
        main:
            pattern: ^/
            form_login:
                login_path:  /login
                check_path:  /login_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        # FOS
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }

