<?php

namespace WAN\MedienFTPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
	public function findRootFiles()
	{
		return $this->getEntityManager()
		->createQuery('SELECT f FROM WANMedienFTPBundle:File f WHERE f.parentFolder IS NULL')
		->getResult();
	}
}
