<?php

namespace WAN\MedienFTPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends EntityRepository
{
	public function findRootFolders()
	{
		return $this->getEntityManager()
			->createQuery('SELECT f FROM WANMedienFTPBundle:Folder f WHERE f.parentFolder IS NULL')
			->getResult();
	}
}
